### ISSUE TITLE
Does not show UPLOAD of streamed file, but says it does

### ISSUE THREAD

**Issue by TheBadEye** [Azure/azure-docs-sdk-java#1256]
[Enter feedback here]

While the page text lists uploading a streamed file as an example, it actually only illustrates enumerating a path, is there a more relevant page illustrating uploading of GEN2 Hierarchical files to containers and directories?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe9440d6-091d-7240-4d91-3db4fc006971
* Version Independent ID: dd6d5daa-37d1-cdde-7db6-9d8066647329
* Content: [Azure File Data Lake client library for Java](https://docs.microsoft.com/en-us/java/api/overview/azure/storage-file-datalake-readme-pre?view=azure-java-stable#upload-a-file-from-a-stream)
* Content Source: [docs-ref-services/storage-file-datalake-readme-pre.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/storage-file-datalake-readme-pre.md)
* Service: **storage**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @maggiepint
* Microsoft Alias: **magpint**

**Comment by pauljewellmsft** [comment]
@TheBadEye So sorry this issue wasn't addressed previously. You've likely found an answer elsewhere by now, but additional docs for Gen2 and Java can be found [here](https://learn.microsoft.com/azure/storage/blobs/data-lake-storage-directory-file-acl-java?tabs=azure-ad).

Again, apologies that this issue was never addressed.
